# This is a basic workflow to help you get started with Actions

name: Modern Pipeline

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-csharp:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target build-csharp -Verbose
      - run: md bin
      - run: Set-Content .\bin\lib.dll 'lib'
      - uses: actions/upload-artifact@v2
        with:
          name: bin
          path: .\bin        
  build-apl-sysobjs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: .\build.ps1 -Target build-apl-sysobjs -Verbose
  sonarqube-scan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target sonarqube-scan -Verbose
  apl-func-chk:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target apl-func-chk -Verbose
  qc-chk-chkinst:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target qc-chk-chkinst -Verbose
  deploy-base-installations:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target deploy-base-installations -Verbose
  package-ims:
    runs-on: windows-latest
    needs: [build-csharp, build-apl-sysobjs]
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target package-ims -Verbose    
  build-scd-media:
    runs-on: windows-latest
    needs: [package-ims]
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target build-scd-media -Verbose    
  update-installations:
    runs-on: windows-latest
    needs: [build-scd-media]
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target update-installations -Verbose    
  run-l0-csharp:
    runs-on: windows-latest
    needs: [build-csharp]
    steps:
      - uses: actions/checkout@v2
      - run: .\build.ps1 -Target run-l0-csharp -Verbose    
      - uses: actions/download-artifact@v2
        with:
          name: bin
      - run: Get-Content .\bin\lib.dll
  run-l1-apl:
    runs-on: windows-latest
    needs: [update-installations]
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target run-l1-apl -Verbose    
  run-l1-csharp:
    runs-on: windows-latest
    needs: [update-installations]
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target run-l1-csarp -Verbose    
  run-l2-apl:
    runs-on: windows-latest
    needs: [update-installations]
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target run-l2-apl -Verbose    
  run-l2-csharp:
    runs-on: windows-latest
    needs: [update-installations]
    steps:
      - uses: actions/checkout@v2
      - name: Run build script
        run: .\build.ps1 -Target run-l2-csharp -verbose    
